duck_tv_app_video:
    resource: "@DuckTVAppBundle/Resources/config/routing/video.yml"
    prefix:   /video

duck_tv_app_category:
    resource: "@DuckTVAppBundle/Resources/config/routing/category.yml"
    prefix:   /categorie

duck_tv_app_broadcast:
    resource: "@DuckTVAppBundle/Resources/config/routing/broadcast.yml"
    prefix:   /diffusion

duck_tv_app_grid:
    resource: "@DuckTVAppBundle/Resources/config/routing/grid.yml"
    prefix:   /grille

duck_tv_app_admin_home:
    path:     /
    defaults:
        _controller: DuckTVAppBundle:Admin:index