duck_tv_app_broadcast_index:
    path:     /
    defaults: { _controller: "DuckTVAppBundle:Broadcast:index" }
    methods:  GET

duck_tv_app_broadcast_show:
    path:     /{id}/afficher
    defaults: { _controller: "DuckTVAppBundle:Broadcast:show" }
    methods:  GET

duck_tv_app_broadcast_new:
    path:     /ajouter
    defaults:
        _controller: "DuckTVAppBundle:Broadcast:new"
    methods:  [GET, POST]

duck_tv_app_broadcast_edit:
    path:     /{id}/editer
    defaults: { _controller: "DuckTVAppBundle:Broadcast:edit" }
    methods:  [GET, POST]

duck_tv_app_broadcast_delete:
    path:     /{id}/supprimer
    defaults: { _controller: "DuckTVAppBundle:Broadcast:delete" }
    methods:  DELETE
