duck_tv_app_category_index:
    path:     /
    defaults: { _controller: "DuckTVAppBundle:Category:index" }
    methods:  GET

duck_tv_app_category_show:
    path:     /{slug}/afficher
    defaults: { _controller: "DuckTVAppBundle:Category:show" }
    methods:  GET

duck_tv_app_category_new:
    path:     /ajouter
    defaults: { _controller: "DuckTVAppBundle:Category:new" }
    methods:  [GET, POST]

duck_tv_app_category_edit:
    path:     /{slug}/editer
    defaults: { _controller: "DuckTVAppBundle:Category:edit" }
    methods:  [GET, POST]

duck_tv_app_category_delete:
    path:     /{slug}/supprimer
    defaults: { _controller: "DuckTVAppBundle:Category:delete" }
    methods:  DELETE
