duck_tv_app_category_index:
    path:     /
    defaults: { _controller: "DuckTVAppBundle:Category:index" }

duck_tv_app_category_show:
    path:     /{slug}/afficher
    defaults: { _controller: "DuckTVAppBundle:Category:show" }

duck_tv_app_category_new:
    path:     /ajouter
    defaults: { _controller: "DuckTVAppBundle:Category:new" }

duck_tv_app_category_edit:
    path:     /{slug}/editer
    defaults: { _controller: "DuckTVAppBundle:Category:edit" }
