duck_tv_app_default_grid:
    path:     /defaut
    defaults:
        _controller: DuckTVAppBundle:Grid:default

duck_tv_app_current_grid:
    path:     /actuelle
    defaults:
        _controller: DuckTVAppBundle:Grid:current

duck_tv_app_next_grid:
    path:     /prochaine
    defaults:
        _controller: DuckTVAppBundle:Grid:next

duck_tv_app_transition_grid:
    path:     /transition
    defaults:
        _controller: DuckTVAppBundle:Grid:transition

duck_tv_app_grid_update:
    path:     /sauvegarder
    defaults:
        _controller: DuckTVAppBundle:Grid:update

duck_tv_app_grid_update_transition:
    path:     /sauvegarder-transition
    defaults:
        _controller: DuckTVAppBundle:Grid:updateTransition

duck_tv_app_grid_fill:
    path:     /remplir
    defaults:
        _controller: DuckTVAppBundle:Grid:fill