duck_tv_app_video_index:
    path:     /
    defaults: { _controller: "DuckTVAppBundle:Video:index" }

duck_tv_app_video_show:
    path:     /{slug}/afficher
    defaults: { _controller: "DuckTVAppBundle:Video:show" }

duck_tv_app_video_new:
    path:     /ajouter
    defaults: { _controller: "DuckTVAppBundle:Video:new" }