# app/config/security.yml

security:
    encoders:
        DuckTV\AppBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # Firewall principal pour le reste de notre site
        main:
            pattern:          ^/
            anonymous:        true
            provider:         fos_userbundle
            form_login:
                login_path:   fos_user_security_login
                check_path:   fos_user_security_check
            logout:
                path:         fos_user_security_logout
                target:       /
            remember_me:
                secret:       %secret%

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }