<?php

namespace DuckTV\AppBundle\Repository;

/**
 * TransitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransitionRepository extends \Doctrine\ORM\EntityRepository
{
}
