duck_tv_app_admin:
    resource: "@DuckTVAppBundle/Resources/config/routing/admin.yml"
    prefix:   /admin

ducktv_app_home:
    path:     /
    defaults:
        _controller: DuckTVAppBundle:Main:index