duck_tv_app_admin:
    resource: "@DuckTVAppBundle/Resources/config/routing/admin.yml"
    prefix:   /admin

duck_tv_app_home:
    path:     /
    defaults:
        _controller: DuckTVAppBundle:FrontApp:index

duck_tv_app_get_videos:
    path:     /recuperer-videos
    defaults:
        _controller: DuckTVAppBundle:FrontApp:getVideos

duck_tv_app_get_weather:
    path:     /recuperer-meteo
    defaults:
        _controller: DuckTVAppBundle:FrontApp:getWeather

# FOSUserBundle : les routes sont encore à personnaliser
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"